// <auto-generated />
using System;
using FrostAura.Reel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace FrostAura.Reel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReelDbContext))]
    [Migration("20260617162050_UserPreferenceTag")]
    partial class UserPreferenceTag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrostAura.Reel.Domain.Auth.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshSessions");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Catalog.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TitleId", "SeasonNumber", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Catalog.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("KnownForDepartment")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePath")
                        .HasColumnType("text");

                    b.Property<long>("TmdbId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Catalog.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AiredEpisodes")
                        .HasColumnType("integer");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text");

                    b.Property<string>("Certification")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstAiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastMetadataRefreshAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Network")
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Subgenres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<long?>("TmdbId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TmdbPopularity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TmdbVoteAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("TmdbVoteCount")
                        .HasColumnType("integer");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("text");

                    b.Property<long?>("TraktId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TraktRating")
                        .HasColumnType("numeric");

                    b.Property<string>("TraktSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TraktVotes")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Genres");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Genres"), "gin");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TmdbPopularity")
                        .IsDescending();

                    b.HasIndex("MediaType", "TmdbId")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" IS NOT NULL");

                    b.HasIndex("MediaType", "TraktId")
                        .IsUnique()
                        .HasFilter("\"TraktId\" IS NOT NULL");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Catalog.TitleAttributes", b =>
                {
                    b.Property<Guid>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Complexity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Darkness")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EmotionalIntensity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EnsembleVsSolo")
                        .HasColumnType("numeric");

                    b.Property<string>("Era")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractorModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExtractorVersion")
                        .HasColumnType("integer");

                    b.Property<decimal>("Humor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Optimism")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Pacing")
                        .HasColumnType("numeric");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<string[]>("Themes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Tone")
                        .HasColumnType("text");

                    b.HasKey("TitleId");

                    b.HasIndex("Status")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("TitleAttributes");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Catalog.TitleCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CastOrder")
                        .HasColumnType("integer");

                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TitleId", "PersonId", "Role")
                        .IsUnique();

                    b.ToTable("TitleCredits");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Catalog.TitleEmbedding", b =>
                {
                    b.Property<Guid>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceTextHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TitleId");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("TitleEmbeddings");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Feed.FeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnchorTitleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExplanationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("FeedSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PredictedRating")
                        .HasColumnType("numeric");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhyThisSentence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeedSnapshotId", "Row", "Rank");

                    b.ToTable("FeedItems");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Feed.FeedSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModelArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("FeedSnapshots");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Filters.ContentFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Kind", "Value")
                        .IsUnique();

                    b.ToTable("ContentFilters");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Library.ShowWatchProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CompletionPct")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastWatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextEpisodeAiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NextEpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("NextEpisodeSeason")
                        .HasColumnType("integer");

                    b.Property<decimal>("ResumeLikelihood")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAiredEpisodes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WatchedEpisodeCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "TitleId")
                        .IsUnique();

                    b.ToTable("ShowWatchProgresses");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Library.UserPersonRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "PersonId")
                        .IsUnique();

                    b.HasIndex("AccountId", "RatedAt");

                    b.ToTable("UserPersonRatings");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Library.UserRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "RatedAt");

                    b.HasIndex("AccountId", "SubjectType", "TitleId", "SeasonNumber", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("UserRatings");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Library.UserTitleReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "TitleId", "Kind")
                        .IsUnique()
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.ToTable("UserTitleReactions");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Library.WatchedTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFullyWatched")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastWatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Plays")
                        .HasColumnType("integer");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "IsFullyWatched");

                    b.HasIndex("AccountId", "TitleId")
                        .IsUnique();

                    b.ToTable("WatchedTitles");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Ml.AccountTasteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("LovedCentroid")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Vector>("RecentCentroid")
                        .HasColumnType("vector(1536)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AccountTasteProfiles");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Ml.EvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaselinePrecisionAt10")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("HoldoutPositiveCount")
                        .HasColumnType("integer");

                    b.Property<bool>("LowSample")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Mae")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ModelPrecisionAt10")
                        .HasColumnType("numeric");

                    b.Property<bool>("PassedGate")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RelativeImprovement")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rmse")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SpearmanRho")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TrainingRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingRunId")
                        .IsUnique();

                    b.ToTable("EvaluationResults");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Ml.ModelArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Algo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ArtifactBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FeatureSchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrainingRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("AccountId", "Version")
                        .IsUnique();

                    b.ToTable("ModelArtifacts");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Ml.PersonAffinity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Affinity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("RatedTitleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "PersonId", "Role")
                        .IsUnique();

                    b.ToTable("PersonAffinities");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Ml.TitleScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContributionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ModelArtifactId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PredictedRating")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ModelArtifactId", "PredictedRating")
                        .IsDescending(false, false, true);

                    b.HasIndex("AccountId", "TitleId", "ModelArtifactId")
                        .IsUnique();

                    b.ToTable("TitleScores");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Ml.TrainingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("HoldoutRowCount")
                        .HasColumnType("integer");

                    b.Property<string>("HyperparamsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Iteration")
                        .HasColumnType("integer");

                    b.Property<decimal>("PositiveThreshold")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SplitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TrainRowCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "StartedAt");

                    b.ToTable("TrainingRuns");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Providers.ProviderLinkPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanaryTitleId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastHttpStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("UrlTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Region");

                    b.ToTable("ProviderLinkPatterns");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Providers.StreamingProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayPriority")
                        .HasColumnType("integer");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TmdbProviderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TmdbProviderId")
                        .IsUnique();

                    b.ToTable("StreamingProviders");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Providers.TitleAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TitleId", "Region");

                    b.HasIndex("TitleId", "Region", "ProviderId", "Kind")
                        .IsUnique();

                    b.ToTable("TitleAvailabilities");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Sync.ExternalApiUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CallCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Day")
                        .HasColumnType("date");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("TokensUsed")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Day")
                        .IsUnique();

                    b.ToTable("ExternalApiUsages");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Sync.ManagedListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemovalReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "TitleId")
                        .IsUnique()
                        .HasFilter("\"RemovedAt\" IS NULL");

                    b.ToTable("ManagedListItems");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Sync.SyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CursorJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<string>("ProgressMessage")
                        .HasColumnType("text");

                    b.Property<decimal?>("ProgressPct")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Kind")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Pending', 'Running')");

                    b.HasIndex("Status", "Priority", "EnqueuedAt");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Sync.TraktConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastActivitiesJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastDeltaSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFullReconcileAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRefreshAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagedListSlug")
                        .HasColumnType("text");

                    b.Property<long?>("ManagedListTraktId")
                        .HasColumnType("bigint");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("TraktConnections");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Sync.TraktOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("TraktOutbox");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Tenancy.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PipelineStage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("PipelineStageChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TraktUserSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TraktUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TraktUserSlug")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Tenancy.UserPreferenceTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Text")
                        .IsUnique();

                    b.ToTable("UserPreferenceTags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("FrostAura.Reel.Domain.Tenancy.Account", b =>
                {
                    b.OwnsOne("FrostAura.Reel.Domain.Tenancy.AccountSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("AccountId");

                            b1.Property<string>("EmailForBilling");

                            b1.Property<string>("MaturityCeiling");

                            b1.Property<bool>("OnboardingCompleted");

                            b1.Property<string>("SettingsPinHash");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts");

                            b1
                                .ToJson("Settings")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
